### PR TITLE
Fix NSTableViewDataSource method signature

### PR DESCRIPTION
**Pull request by tonyarnold**
I botched one of the NSTableViewDataSource methods in #372 - the return type of the method needed to be `Any?` not `AnyObject?`.

### CODE REVIEW

**Comment by srdanrasic** [comment]
Ah, cool :) I guess in that case we can also loosen the extensions constraint be removing `Element.DataSource.Item: AnyObject`.

**Comment by tonyarnold** [comment]
Does it need to be `Optional<Any>`, given the return type is optional? I'm still not 100% across how generic constraints work.

**Comment by srdanrasic** [comment]
I don't think we need, because one will be able to get that by doing `Array<String?>` so `Item` will be `String?`.

**Comment by tonyarnold** [comment]
OK, makes sense. Thanks!

**Pull request merged**
