### PR TITLE
Update Diff.swift to v0.5.1

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR updates Diff.swift to v0.5.1, and removes the unnecessary restriction to Diff.swift v0.4.x.

### CODE REVIEW

**Comment by srdanrasic** [comment]
I wander why the tests are failing. Any idea?

**Comment by tonyarnold** [comment]
I'm looking at the tests now. Travis is such a time sink :(

**Comment by srdanrasic** [comment]
Don't worry about this too much @tonyarnold, I'll also have a look. :)

**Comment by tonyarnold** [comment]
That'd be great. Travis is slow tonight, so it's not quick to check that the workarounds I'm adding are actually having any success.

**Comment by tonyarnold** [comment]
Far out: it finally passed.

**Comment by srdanrasic** [comment]
Thanks @tonyarnold!

**Pull request merged**
