### PR TITLE
Change NSControl.reactive.controlEvent to emit the sender, rather than objectValue

### PR DESCRIPTION
**Pull request by tonyarnold**
I'm a little torn on this change, but I think it would be better if `NSControl.reactive.controlEvent` emitted the sending control (`sender`), rather than casting the `objectValue` property to `AnyObject?`. 

Not all AppKit controls emit useful or meaningful control state information via `objectValue` (`NSPopUpButton` being one example). 

With this change, the developer can choose what they want to interrogate from the sending control. 

Thoughts?

### CODE REVIEW

**Comment by tonyarnold** [comment]
I also have to say, I'm unsure whether to expose things like `NSButton.reactive.state` as `DynamicSubject<Int>`. It's _really_ common to bind the value of a button to something like `UserDefaults` in traditional Cocoa Bindings. I guess it could be considered similar to `NSTextView.reactive.string`? 

I have wrappers around my user defaults that look similar to:

```swift
import Foundation
import ReactiveKit
import Bond

struct UserDefaultsKey {
    static let showCanvasInformationMessages = "ShowCanvasInformationMessages"
}

public extension ReactiveExtensions where Base: UserDefaults {

    public var showCanvasInformationMessages: DynamicSubject<Bool> {
        return dynamicSubject(
            signal: self.keyPath(UserDefaultsKey.showCanvasInformationMessages, ofType: Optional<Bool>.self).eraseType(),
            get: { $0.bool(forKey: UserDefaultsKey.showCanvasInformationMessages) },
            set: { $0.set($1, forKey: UserDefaultsKey.showCanvasInformationMessages) }
        )
    }
}
```

So when I following the currently implemented pattern, it looks like:

```swift
self.showCanvasInformationMessagesButton.reactive
    .controlEvent
    .map { $0.state == NSOnState }
    .bind(to: UserDefaults.standard.reactive.showCanvasInformationMessages)

UserDefaults.standard.reactive
    .showCanvasInformationMessages
    .map { $0 ? NSOnState : NSOffState }
    .bind(to: self.showCanvasInformationMessagesButton.reactive.state)
```

If `NSButton.reactive.state` were a `DynamicSubject` it could be:

```swift
self.showCanvasInformationMessagesButton.reactive.state
    .bidirectionalMap(
        to: { $0 == NSOnState },
        from: { $0 ? NSOnState : NSOffState }
    )
    .bidirectionalBind(to: UserDefaults.standard.reactive.showCanvasInformationMessages)
```

**Comment by srdanrasic** [comment]
If that's the case, sending NSControl itself sounds like an on solution, but may I also suggest another one. Let the user specify interrogation closure

```swift 
public func controlEvent<T>(_ read: @escaping (NSControl) -> T) -> SafeSignal<T>
```

so that he can do

```swift
control.controlEvent { $0.integerValue }.observeNext { number in ... } 
```

But you are the master of AppKit, you choose :)

As for the second question, `NSButton.reactive.state` as `DynamicSubject<Int>` sounds reasonable. Because you are using KVO, just make sure that you are not missing `triggerEventOnSetting: false` in `dynamicSubject(...)`.

If doing `$0.set($1, forKey: UserDefaultsKey.showCanvasInformationMessages)` triggers event on `self.keyPath(UserDefaultsKey.showCanvasInformationMessages, ofType: Optional<Bool>.self).eraseType()`, then you need to set `triggerEventOnSetting: false` or you'll end up with duplicate events :)

**Comment by tonyarnold** [comment]
Thanks for the KVO tip - I hadn't seen the `triggerEventOnSetting` parameter - that's nice!

As to the NSControl event - I don't think it's onerous for the user to map the control to extract the desired value themselves. Your suggestion is good - I've included it in addition to the plain property. 

I should probably properly document all of these Bonds and Subjects I'm adding…

**Comment by srdanrasic** [comment]
It's not imperative as most of those extensions are just reactive representations of corresponding properties. I'm merging this, thanks @tonyarnold!

**Pull request merged**
