### PR TITLE
Adjust project source layout to support Swift Package Manager

### PR DESCRIPTION
**Pull request by tonyarnold**
OK, this is a big one - in order to properly support Swift Package Manager, the filesystem layout for the project needs to be update (see #406 for more detail).

I'm happy to discuss or modify things in this PR, or to reject it entirely if it's seen as too onerous a change.

### CODE REVIEW

**Comment by tonyarnold** [comment]
You can test these changes by building/testing as normal from within Xcode, Carthage and CocoaPods, then on the command line:

```sh
swift build
swift test
```

**Comment by srdanrasic** [comment]
This is awesome job @tonyarnold! 🎉 

I could not get it compiling though. Here is a screenshot. I made a clean build (deleted DerivedData too).

screen shot 2017-04-02 at 10 09 26

There seems to be some issues with BNDProtocolProxyBase target. I was able to get macOS target building with some combination of building dependencies first, but iOS still has issues, hmm. 

Thinking now... Do we even need BNDProtocolProxyBase as a separate target in Xcode project? It makes sense to have it with SPM, but in Xcode project could we just make BNDProtocolProxyBase.h and BNDProtocolProxyBase.m part of Bond-iOS/tvOS/maxOS targets like they were before. 

We would then import the target only if building with SPM. To do that, we could define `-DIS_XCODE_BUILD` in Other Swift Flags and in `s.compiler_flags = '-DIS_XCODE_BUILD'` in Podspec and then import if it is not set.

```swift
#if !IS_XCODE_BUILD
  import BNDProtocolProxyBase
#endif
```

What do you think?

**Comment by tonyarnold** [comment]
@srdanrasic good suggestion. I've done that in the latest commits against this branch. 

Here's hoping Swift Package Manager allows more flexible directory layouts in v4 🎉

**Comment by srdanrasic** [comment]
Yup. I'd really love to see it more integrated with Xcode and with support for all platforms too.

Thanks for this updates! Everything seems to work now so I'll merge and release.

**Pull request merged**
